const actionTypes = {
  USER_LOGIN_REQ: 'USER_LOGIN_REQ',
  USER_LOGIN_OK: 'USER_LOGIN_OK',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_LOGOUT_REQ: 'USER_LOGOUT_REQ',
  USER_LOGOUT_OK: 'USER_LOGOUT_OK',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
}

export default actionTypes;
